---
# vars file for miniconda


_miniconda_url:
  default:  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh


miniconda_url: "{{ _miniconda_url[ansible_os_family] | default(_miniconda_url['default']) }}"


miniconda_home: '~/miniconda'

miniconda_modify_path: no
miniconda_rcfile: '~/.bashrc'

miniconda_add_condarc: yes
