- name: system setup | development packages | conda
  tags: dev,development,packages,conda
  when: miniconda is defined and miniconda == true
  block:
    - name: system setup | development packages | conda | download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
        checksum: md5:a946ea1d0c4a642ddf0c3a26a18bb16d
        mode: 0550
    
    - name: system setup | development packages | conda | create conda folder
      file:
        path: /opt/miniconda3
        state: directory
        mode: 755
        recurse: yes
    
    - name: system setup | development packages | conda | run the installer
      shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3
    
    - name: system setup | development packages | conda | Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh
    
    - name: system setup | development packages | conda | add miniconda bin to path
      shell: echo 'export PATH=/opt/miniconda3/bin:$PATH' >> /etc/profile
    
    - name: system setup | development packages | conda | conda - read permission for all
      file:
        path: /opt/miniconda3
        mode: +r
        recurse: yes
    
    - name: system setup | development packages | conda | conda - execution permission for all
      file:
        path: /opt/miniconda3/bin
        mode: +x
        recurse: yes
