- name: system setup | development packages | python | install packages
  tags: dev,development,packages,python
  package:
    name:
      - "{{ python_flake8_package }}"
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_pyflakes_package }}"
      - python-setuptools
      - "{{ python_virtualenv_package }}"
    state: latest
