- name: system setup | development packages | Rust | check for package
  tags: dev,development,packages,rust
  package_facts:
    manager: auto

- name: system setup | development packages | Rust | install packages 
  tags: dev,development,packages,rust
  when: 
    - " 'rustc' not in ansible_facts.packages"
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path -q"
