# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  #- import_tasks: users/riccardo.yml
  #- import_tasks: users/root.yml

  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_utilities.yml
  - import_tasks: software/python.yml
  - import_tasks: software/R.yml
  - import_tasks: software/rust.yml
  - import_tasks: software/miniconda.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/microcode.yml
  - import_tasks: system_setup/openssh.yml

  rescue:
    - set_fact: task_failed=true
