- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - "{{ cron_package }}"
    state: latest

- name: system setup | cron | install cron extensions | Fedora
  tags: cron
  dnf:
    name: cronie-anacron
    state: present
  when: ansible_distribution == "Fedora"
